# Generated by Django 3.1.7 on 2021-04-16 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_group_id', models.IntegerField()),
                ('access_group_name', models.CharField(max_length=100)),
                ('basic_product_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('modified', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('structure_decode', models.BooleanField()),
                ('total_uses', models.IntegerField()),
                ('sessions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='api.session')),
            ],
        ),
    ]
